### ISSUE TITLE
Add `youtube-dl` or `yt-dlp` as `rde` feature?

### ISSUE THREAD

**Issue by johanengstrand** [engstrand-config/guix-dotfiles#15]

**Comment by abcdw** [comment]
Hello guys!

I guess this one and a few more features from other issues are available upstream now! :)

**Comment by Frewacom** [comment]
Thanks for letting us know @abcdw.

Really inspiring work on both rde and Guix Home, keep it up! 👍🏼

**Comment by abcdw** [comment]
Really glad to hear it!)

A small note: in the README there is a missing ~ before username in rde link.

From what I see, you guys do some exetensive scheme development, including expansion of some rde functionality, dwl-guile development and a few other things. Recently, we added gider package (it's built on top of some geiser functionality right now), which allows to [run tests](https://youtu.be/KD77Mo4ssIc?t=193) in REPL using emacs interaface and shorten feedback loop or implement convenient TDD.

Also, don't hesistate to come to rde-devel from time to time to share your points of view, pain points, participate in the decisions and do anything else, I will be really glad to see a feedback and ideas from so experienced rde people and I think such interactions can be very valuable for everyone. If you have time and desire of course :)

BTW, there is a `feature-emacs-evil` landed in `(contrib features emacs-xyz)` a few weeks ago, which can be interesting for you.
