### ISSUE TITLE
Toys Channel Search Add Channel

### ISSUE THREAD

**Issue by jgarte** [engstrand-config/guix-dotfiles#30]
Hi,

WDYT of adding `guix-dotfiles` as a channel to toys channel search here?

https://toys.whereis.みんな/

There's a lot of great stuff here that would be more easily discoverable by others that way.

**Comment by johanengstrand** [comment]
Hey,

Sure, why not? Looks like we would be in good company :)

**Comment by jgarte** [comment]
Cool! 

Would you be able to send a patch to [~whereiseveryone/toys@lists.sr.ht](https://git.sr.ht/~whereiseveryone/toys#contribute)?

See this commit by roptat on how to add a [toys-box](https://git.sr.ht/~whereiseveryone/toys/commit/bd630253a2d81859d92dcb48a50132648e6ab330) ;()

[unwox](https://unwox.com/) or I can merge it.

**Comment by johanengstrand** [comment]
Done, I think I got it right.

**Comment by jgarte** [comment]
[unwox](https://unwox.com/) merged it. Thanks for sending the patch! See ya around
